nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmScopes:
  barmer-puls:
    npmAlwaysAuth: true
    npmRegistryServer: "https://repo.entw.bconnect.barmer.de/artifactory/api/npm/npm/"
