import { css } from "@ethr/core";

export const fonts = css.defineVars({
  familySans: '"Noto Sans", sans-serif',
  familySerif: '"Noto Serif", sans',
  size0: "12px",
  size1: "14px",
  size2: "16px",
  size3: "20px",
  size4: "24px",
  size5: "32px",
  size6: "44px",
  weightRegular: 400,
  weightSemibold: 600,
  weightBold: 700,
});

export const typography = css.create({
  headingH1: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size6,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.5,
    lineHeight: 48 / 44,
  },
  headingH2: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size5,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.5,
    lineHeight: 40 / 32,
  },
  headingH3: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size4,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.5,
    lineHeight: 32 / 24,
  },
  headingH4: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size3,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.5,
    lineHeight: 24 / 20,
  },
  headingH5: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size2,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.25,
    lineHeight: 24 / 16,
  },
  headingH6: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size1,
    fontWeight: fonts.weightBold,
    letterSpacing: -0.25,
    lineHeight: 20 / 14,
  },
  bodyLarge: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size2,
    fontWeight: fonts.weightRegular,
    letterSpacing: -0.25,
    lineHeight: 24 / 16,
  },
  bodySmall: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size1,
    fontWeight: fonts.weightRegular,
    letterSpacing: -0.25,
    lineHeight: 20 / 14,
  },
  bodyMicro: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size0,
    fontWeight: fonts.weightRegular,
    letterSpacing: -0.25,
    lineHeight: 16 / 12,
  },
  utilityButtonLarge: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size2,
    fontWeight: fonts.weightSemibold,
    letterSpacing: -0.25,
    lineHeight: 24 / 16,
  },
  utilityButtonSmall: {
    fontFamily: fonts.familySans,
    fontSize: fonts.size1,
    fontWeight: fonts.weightSemibold,
    letterSpacing: -0.25,
    lineHeight: 20 / 14,
  },
});
